/**
 * Bingo Show V2 — Assets Module (Next.js Web Edition)
 * Mapeia todos os 333+ assets visuais em 4x/2x para a pasta publica /bingoshow-v2.
 */

const BASE = '/bingoshow-v2';

export const BingoShowAssets = {
  backgrounds: {
    bgSpace: `${BASE}/backgrounds/4x/bg-space.png`,
    bgGlow: `${BASE}/backgrounds/4x/bg-glow.png`,
    bgMain: `${BASE}/backgrounds/4x/bg-main.png`,
    bgBlueGradient: `${BASE}/backgrounds/4x/bg-blue-gradient.png`,
  },
  balls: {
    blue: {
      default: `${BASE}/balls/4x/ball-blue-default.png`,
      pressed: `${BASE}/balls/4x/ball-blue-pressed.png`,
      selected: `${BASE}/balls/4x/ball-blue-selected.png`,
      focused: `${BASE}/balls/4x/ball-blue-focused.png`,
      glow: `${BASE}/balls/4x/ball-blue-glow.png`,
      transparent: `${BASE}/balls/4x/ball-blue-transparent.png`,
      winner: `${BASE}/balls/4x/ball-blue-winner.png`,
    },
    gold: {
      default: `${BASE}/balls/4x/ball-gold-default.png`,
      pressed: `${BASE}/balls/4x/ball-gold-pressed.png`,
      selected: `${BASE}/balls/4x/ball-gold-selected.png`,
      focused: `${BASE}/balls/4x/ball-gold-focused.png`,
      glow: `${BASE}/balls/4x/ball-gold-glow.png`,
      transparent: `${BASE}/balls/4x/ball-gold-transparent.png`,
      winner: `${BASE}/balls/4x/ball-gold-winner.png`,
    },
    green: {
      default: `${BASE}/balls/4x/ball-green-default.png`,
      pressed: `${BASE}/balls/4x/ball-green-pressed.png`,
      selected: `${BASE}/balls/4x/ball-green-selected.png`,
      focused: `${BASE}/balls/4x/ball-green-focused.png`,
      glow: `${BASE}/balls/4x/ball-green-glow.png`,
      transparent: `${BASE}/balls/4x/ball-green-transparent.png`,
      winner: `${BASE}/balls/4x/ball-green-winner.png`,
    },
    red: {
      default: `${BASE}/balls/4x/ball-red-default.png`,
      pressed: `${BASE}/balls/4x/ball-red-pressed.png`,
      selected: `${BASE}/balls/4x/ball-red-selected.png`,
      focused: `${BASE}/balls/4x/ball-red-focused.png`,
      glow: `${BASE}/balls/4x/ball-red-glow.png`,
      transparent: `${BASE}/balls/4x/ball-red-transparent.png`,
      winner: `${BASE}/balls/4x/ball-red-winner.png`,
    },
    yellow: {
      default: `${BASE}/balls/4x/ball-yellow-default.png`,
      pressed: `${BASE}/balls/4x/ball-yellow-pressed.png`,
      selected: `${BASE}/balls/4x/ball-yellow-selected.png`,
      focused: `${BASE}/balls/4x/ball-yellow-focused.png`,
      glow: `${BASE}/balls/4x/ball-yellow-glow.png`,
      transparent: `${BASE}/balls/4x/ball-yellow-transparent.png`,
      winner: `${BASE}/balls/4x/ball-yellow-winner.png`,
    },
    purple: {
      default: `${BASE}/balls/4x/ball-purple-default.png`,
      pressed: `${BASE}/balls/4x/ball-purple-pressed.png`,
      selected: `${BASE}/balls/4x/ball-purple-selected.png`,
      focused: `${BASE}/balls/4x/ball-purple-focused.png`,
      glow: `${BASE}/balls/4x/ball-purple-glow.png`,
      transparent: `${BASE}/balls/4x/ball-purple-transparent.png`,
      winner: `${BASE}/balls/4x/ball-purple-winner.png`,
    },
    silver: {
      default: `${BASE}/balls/4x/ball-silver-default.png`,
      pressed: `${BASE}/balls/4x/ball-silver-pressed.png`,
      selected: `${BASE}/balls/4x/ball-silver-selected.png`,
      focused: `${BASE}/balls/4x/ball-silver-focused.png`,
      glow: `${BASE}/balls/4x/ball-silver-glow.png`,
      transparent: `${BASE}/balls/4x/ball-silver-transparent.png`,
      winner: `${BASE}/balls/4x/ball-silver-winner.png`,
    },
  },
  effects: {
    glowBlue: `${BASE}/effects/4x/effect-glow-blue.png`,
    lightBurst: `${BASE}/effects/4x/effect-light-burst.png`,
    shine: `${BASE}/effects/4x/effect-shine.png`,
    bloom: `${BASE}/effects/4x/effect-bloom.png`,
    glowGold: `${BASE}/effects/4x/effect-glow-gold.png`,
    innerGlow: `${BASE}/effects/4x/effect-inner-glow.png`,
    outerGlow: `${BASE}/effects/4x/effect-outer-glow.png`,
    glassHighlight: `${BASE}/effects/4x/effect-glass-highlight.png`,
    lightSweep: `${BASE}/effects/4x/effect-light-sweep.png`,
    reflection: `${BASE}/effects/4x/effect-reflection.png`,
  },
  borders: {
    neonBlue: `${BASE}/borders/4x/border-neon-blue.png`,
    neonGold: `${BASE}/borders/4x/border-neon-gold.png`,
    glass: `${BASE}/borders/4x/border-glass.png`,
    winner: `${BASE}/borders/4x/border-winner.png`,
  },
  textures: {
    space: `${BASE}/textures/2x/texture-space.png`,
    noise: `${BASE}/textures/2x/texture-noise.png`,
    gradientOverlay: `${BASE}/textures/2x/texture-gradient-overlay.png`,
    glass: `${BASE}/textures/2x/texture-glass.png`,
    dark: `${BASE}/textures/2x/texture-dark.png`,
    blue: `${BASE}/textures/2x/texture-blue.png`,
  },
  decorative: {
    cornerTopLeftBlue: `${BASE}/decorative/2x/deco-corner-tl-blue.png`,
    cornerTopLeftGold: `${BASE}/decorative/2x/deco-corner-tl-gold.png`,
    cornerTopRightGold: `${BASE}/decorative/2x/deco-corner-tr-gold.png`,
    coinStack: `${BASE}/decorative/4x/deco-coin-stack.png`,
  },
  cards: {
    jackpot: `${BASE}/cards/4x/card-jackpot.png`,
    ticket: `${BASE}/cards/4x/card-ticket.png`,
    tableHeader: `${BASE}/cards/4x/card-table-header.png`,
    tableRow: `${BASE}/cards/4x/card-table-row.png`,
    ranking: `${BASE}/cards/4x/card-ranking.png`,
    prize: `${BASE}/cards/4x/card-prize.png`,
    prizeValue: `${BASE}/cards/4x/card-prize-value.png`,
    metadata: `${BASE}/cards/4x/card-metadata.png`,
    metadataGold: `${BASE}/cards/4x/card-metadata-gold.png`,
    metadataGreen: `${BASE}/cards/4x/card-metadata-green.png`,
    topWinners: `${BASE}/cards/4x/card-top-winners.png`,
    prizeLineGold: `${BASE}/cards/4x/card-prize-line1-gold.png`,
    prizeLineCyan: `${BASE}/cards/4x/card-prize-line2-cyan.png`,
    prizeBingoGreen: `${BASE}/cards/4x/card-prize-bingo-green.png`,
  },
  framesTopWinners: {
    cornerTL: `${BASE}/cards/9slice/topwinners-corner-tl.png`,
    cornerTR: `${BASE}/cards/9slice/topwinners-corner-tr.png`,
    cornerBL: `${BASE}/cards/9slice/topwinners-corner-bl.png`,
    cornerBR: `${BASE}/cards/9slice/topwinners-corner-br.png`,
    center: `${BASE}/cards/9slice/topwinners-center.png`,
    topLeft: `${BASE}/cards/9slice/topwinners-top-left.png`,
    topSpark: `${BASE}/cards/9slice/topwinners-top-spark.png`,
    topRight: `${BASE}/cards/9slice/topwinners-top-right.png`,
    bottomLeft: `${BASE}/cards/9slice/topwinners-bottom-left.png`,
    bottomSpark: `${BASE}/cards/9slice/topwinners-bottom-spark.png`,
    bottomRight: `${BASE}/cards/9slice/topwinners-bottom-right.png`,
    leftTop: `${BASE}/cards/9slice/topwinners-left-top.png`,
    leftSpark: `${BASE}/cards/9slice/topwinners-left-spark.png`,
    leftBottom: `${BASE}/cards/9slice/topwinners-left-bottom.png`,
    rightTop: `${BASE}/cards/9slice/topwinners-right-top.png`,
    rightSpark: `${BASE}/cards/9slice/topwinners-right-spark.png`,
    rightBottom: `${BASE}/cards/9slice/topwinners-right-bottom.png`,
  },
  framesBannerBlue: {
    cornerTL: `${BASE}/cards/9slice/bannerblue2-corner-tl.png`,
    cornerTR: `${BASE}/cards/9slice/bannerblue2-corner-tr.png`,
    cornerBL: `${BASE}/cards/9slice/bannerblue2-corner-bl.png`,
    cornerBR: `${BASE}/cards/9slice/bannerblue2-corner-br.png`,
    center: `${BASE}/cards/9slice/bannerblue2-center.png`,
    topLeft: `${BASE}/cards/9slice/bannerblue2-top-left.png`,
    topSpark: `${BASE}/cards/9slice/bannerblue2-top-spark.png`,
    topRight: `${BASE}/cards/9slice/bannerblue2-top-right.png`,
    bottomLeft: `${BASE}/cards/9slice/bannerblue2-bottom-left.png`,
    bottomSpark: `${BASE}/cards/9slice/bannerblue2-bottom-spark.png`,
    bottomRight: `${BASE}/cards/9slice/bannerblue2-bottom-right.png`,
    left: `${BASE}/cards/9slice/bannerblue2-left.png`,
    right: `${BASE}/cards/9slice/bannerblue2-right.png`,
  },
  // footerblue — mesmo formato de 13 peças do framesBannerBlue (corner x4, center,
  // top-left/spark/right, bottom-left/spark/right, left/right) usado pro popup de
  // ganhador (`BingoShowWinnerPopup`), pedido explícito do usuário.
  framesFooterBlue: {
    cornerTL: `${BASE}/cards/9slice/footerblue-corner-tl.png`,
    cornerTR: `${BASE}/cards/9slice/footerblue-corner-tr.png`,
    cornerBL: `${BASE}/cards/9slice/footerblue-corner-bl.png`,
    cornerBR: `${BASE}/cards/9slice/footerblue-corner-br.png`,
    center: `${BASE}/cards/9slice/footerblue-center.png`,
    topLeft: `${BASE}/cards/9slice/footerblue-top-left.png`,
    topSpark: `${BASE}/cards/9slice/footerblue-top-spark.png`,
    topRight: `${BASE}/cards/9slice/footerblue-top-right.png`,
    bottomLeft: `${BASE}/cards/9slice/footerblue-bottom-left.png`,
    bottomSpark: `${BASE}/cards/9slice/footerblue-bottom-spark.png`,
    bottomRight: `${BASE}/cards/9slice/footerblue-bottom-right.png`,
    left: `${BASE}/cards/9slice/footerblue-left.png`,
    right: `${BASE}/cards/9slice/footerblue-right.png`,
  },
  panels: {
    footerComplete: `${BASE}/panels/4x/panel-footer-complete.png`,
    glass: `${BASE}/panels/4x/panel-glass.png`,
    header: `${BASE}/panels/4x/panel-header.png`,
    footer: `${BASE}/panels/4x/panel-footer.png`,
    neon: `${BASE}/panels/4x/panel-neon.png`,
    dark: `${BASE}/panels/4x/panel-dark.png`,
    main: `${BASE}/panels/4x/panel-main.png`,
    modal: `${BASE}/panels/4x/panel-modal.png`,
    popup: `${BASE}/panels/4x/panel-popup.png`,
    sidebar: `${BASE}/panels/4x/panel-sidebar.png`,
  },
  particles: {
    confetti: `${BASE}/particles/4x/particle-confetti.png`,
    gold: `${BASE}/particles/4x/particle-gold.png`,
    sparkles: `${BASE}/particles/4x/particle-sparkles.png`,
    stars: `${BASE}/particles/4x/particle-stars.png`,
    singleGold: `${BASE}/particles/2x/particle-single-gold.png`,
    singleSparkle: `${BASE}/particles/2x/particle-single-sparkle.png`,
    singleBlue: `${BASE}/particles/2x/particle-single-blue.png`,
    singleWhite: `${BASE}/particles/2x/particle-single-white.png`,
  },
  stage: {
    countdownPanel: `${BASE}/stage/4x/stage-countdown-panel.png`,
  },
  jackpot: {
    artwork: `${BASE}/jackpot/4x/jackpot-artwork.png`,
    star: `${BASE}/jackpot/4x/jackpot-star.png`,
    panel: `${BASE}/jackpot/4x/01_JACKPOT_PANEL.png`,
  },
  logos: {
    badge: `${BASE}/logos/4x/logo-badge.png`,
  },
};

export default BingoShowAssets;
